name: wine
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - scikit-learn
    - jupyterlab
    - requests
    - yapf
    - pylint
    - dvc
    - dvclive
    - ucimlrepo